//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string SearchQuery { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> IsOnline { get; set; }
    }
}
